/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-24 04:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TestGIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642397204384L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("utf-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html;charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=10\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Web GIS</title>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .input0 {\r\n");
      out.write("    	width: 290px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        background-color: #b0aea9;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        readnoly;\r\n");
      out.write("    }\r\n");
      out.write("    .button1 {\r\n");
      out.write("    	width: 30%;\r\n");
      out.write("        height: 55px;\r\n");
      out.write("        background-color: gold;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .button2 {\r\n");
      out.write("    	width: 30%;\r\n");
      out.write("        height: 55px;\r\n");
      out.write("        background-color: #5cb85c;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .button3 {\r\n");
      out.write("    	width: 30% ;\r\n");
      out.write("        height: 55px;\r\n");
      out.write("        background-color: #34aeeb;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .button4 {\r\n");
      out.write("    	width: 20%;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        background-color: #c9302c;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .button5 {\r\n");
      out.write("    	width: 93%;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        background-color: #c9302c;\r\n");
      out.write("        border: 3px solid black;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<!--\r\n");
      out.write("	<nav class=\"navbar-static-top\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"#\">유해물질 재난안전 정보 확인 서비스</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	-->\r\n");
      out.write("	<!-- contents -->\r\n");
      out.write("	<div id=\"page-content-wrapper\">\r\n");
      out.write("<!-- \r\n");
      out.write("		<div id=\"alarm-dim-layer\" class=\"dim-layer\">\r\n");
      out.write("		    <div class=\"dimBg\"></div>\r\n");
      out.write("		    <div id=\"layer2\" class=\"pop-layer\">\r\n");
      out.write("		        <div class=\"pop-container\">\r\n");
      out.write("		            <div class=\"pop-conts\">\r\n");
      out.write("		                <p class=\"ctxt mb20\">유해물질 유출 대피 알림<br>염화티오닐(Thionyl chloride)</p>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write(" -->\r\n");
      out.write("		<div id=\"msg-dim-layer\" class=\"dim-layer\">\r\n");
      out.write("		    <div class=\"dimBg\"></div>\r\n");
      out.write("		    <div id=\"layer2\" class=\"pop-layer\">\r\n");
      out.write("		    	<div class=\"closeX closeXp\">x</div>\r\n");
      out.write("		        <div class=\"pop-container\">\r\n");
      out.write("		            <div class=\"pop-conts\">\r\n");
      out.write("		                <p class=\"ctxt mb20\"></p>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"map\">\r\n");
      out.write("			<canvas id=\"windyMap\" class=\"fill\"></canvas>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"pixel_box\">\r\n");
      out.write("				<div class=\"closeX\">x</div>\r\n");
      out.write("				<div id=\"overlay-ses\"></div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("							\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("<!-- \r\n");
      out.write("			<div id=\"pixel_box1\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">사고정보</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses2\">\r\n");
      out.write("					<div class=\"category\">\r\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px;\">\r\n");
      out.write("							<div class=\"item-title fl w-30\"><h4>발생시각 : </h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\" id=\"currentTime\"><h4></h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item cf\">\r\n");
      out.write("							<div class=\"item-title fl w-30\"><h4>사고진행 : </h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\" id=\"runningTime\"><h4></h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item cf\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("							<button id=\"res2accident\" type=\"button\" class=\"btn btn-danger\" style=\"width: 45%; height: 30px;\">대응요령</button>\r\n");
      out.write("							<button id=\"resSystem\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 30px; margin-left: 5px;margin-right:10px\">대응체계</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write(" -->\r\n");
      out.write(" <!--\r\n");
      out.write("			<div id=\"pixel_box4\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">지도 on/off</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses2\" style=\"padding-top: 5px;\">\r\n");
      out.write("					<div class=\"category\">\r\n");
      out.write("						<div class=\"item cf\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("							<button id=\"map_onoff_spread\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 40px;\">확산 Map on</button>\r\n");
      out.write("							<button id=\"map_onoff_wind\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 40px; margin-left: 5px;margin-right:10px\">바람 Map on</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write(" -->\r\n");
      out.write(" <!--	\r\n");
      out.write("			<div id=\"pixel_box2\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">대응상황</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses3\">\r\n");
      out.write("					<div class=\"category\">\r\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px; background-color: #d9534f\">\r\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>1단계</h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>화학사고 발생,<br>사고접수 및 전파</h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\r\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\r\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>2단계</h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>위기대응반 가동</h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\r\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\r\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>3단계</h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>화학사고 수습본부<br>설치 및 사고수습</h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\r\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\r\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>4단계</h4></div>\r\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>사고지역 복구 및<br>사고 후 영향조사,<br>종료</h4></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("<!--				\r\n");
      out.write("			<div id=\"pixel_box3\">\r\n");
      out.write("				<div class=\"closeX\">x</div>\r\n");
      out.write("				<div id=\"overlay-ses2\" style=\"padding-left: 10px;\">\r\n");
      out.write("					<div class=\"category\">\r\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px;\">\r\n");
      out.write("							<img id=\"pixel_box3_img\" src=\"resources/images/res2accident.PNG\" style=\"width: 700px; padding-right: 10px; padding-bottom: 10px;\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrapper\" class=\"toggled\">\r\n");
      out.write("<!-- 	전체 -->\r\n");
      out.write("		<nav id=\"sidebar-wrapper\"> \r\n");
      out.write("<!-- 	위차찾기 -->\r\n");
      out.write("			<div class=\"accordion-group panel\">  \r\n");
      out.write("				<div class=\"panel-heading\" data-parent=\"#sidebar-wrapper\" href=\"#collapse1\">\r\n");
      out.write("					<h4 class=\"panel-title\"><a href=\"#\">  위치 선택</a></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse1\" class=\"collapse in\">\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						<div style=\"padding-top: 15px\" />\r\n");
      out.write("						<div style=\"display: flex; justify-content: space-between;\">\r\n");
      out.write("							<input id=\"input0\" class=\"input0\" type=\"text\" placeholder=\"위치\" readonly/>\r\n");
      out.write("							<input class=\"button4\" type=\"button\" onClick=\"thorwItem();\" value=\" × \"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"padding-top: 15px\" />\r\n");
      out.write("						<input id=\"input1\"  class=\"input0\" type=\"text\" placeholder=\"위치\" readonly/>\r\n");
      out.write("						<div style=\"padding-top: 15px\" />\r\n");
      out.write("						<input id=\"input2\"  class=\"input0\" type=\"text\" placeholder=\"위치\" value=\"\" readonly style=\"background-color:black;\"/>\r\n");
      out.write("						<div style=\"padding-top: 15px\" />\r\n");
      out.write("						<input id=\"input3\"  class=\"input0\" type=\"text\" placeholder=\"위치\" value=\"\" readonly style=\"background-color:black;\"/>\r\n");
      out.write("						<div style=\"padding-top: 15px\" />\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<div id=\"threeButton\">\r\n");
      out.write("							<button type=\"button\" class=\"button1\" > – </button>\r\n");
      out.write("							<button type=\"button\" class=\"button2\" > + </button>\r\n");
      out.write("							<input  type=\"button\" class=\"button3\" onClick=\"goPopup();\" value=\"위치 추가\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br/>\r\n");
      out.write("						<input  type=\"button\" class=\"button5\" onClick=\"searchCenter();\" value=\"위치 탐색\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br/>\r\n");
      out.write("			<br/>\r\n");
      out.write("			<div class=\"accordion-group panel\">\r\n");
      out.write("				<div class=\"panel-heading\" data-parent=\"#sidebar-wrapper\" href=\"#collapse2\">\r\n");
      out.write("					<h4 class=\"panel-title\"><a href=\"#\">사고 상세 정보</a></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse2\" class=\"collapse in\">\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<table style=\"width:100%\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width:30%; padding-bottom:10px\">사고위치 :</td>\r\n");
      out.write("									<td id=\"accident\" style=\"width:70%; padding-bottom: 10px;\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width:30%; padding-bottom:10px\">사고물질 :</td>\r\n");
      out.write("									<td id=\"accidentMatrial\" style=\"width:70%; padding-bottom: 10px;\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<tr style=\"border-bottom: 1px solid white;\"><td colspan=\"2\"></tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td rowspan=\"3\" style=\"width:30%; padding-bottom:10px\">확산예상범위 :<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(위험도)</td>\r\n");
      out.write("									<td style=\"width:70%;\">\r\n");
      out.write("										<span id=\"accident_area1\" style=\"background-color: #d9534f;display: block; padding-left: 10px; line-height: 30px;\"></span>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width:70%;\">\r\n");
      out.write("										<span id=\"accident_area2\" style=\"background-color: #ded30a;display: block; padding-left: 10px; line-height: 30px;\"></span>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width:70%;\">\r\n");
      out.write("										<span id=\"accident_area3\" style=\"background-color: #5cb85c;display: block; padding-left: 10px; line-height: 30px;\"></span>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div style=\"width: 100%; border-bottom: 1px solid white; padding-top: 10px;\"></div>\r\n");
      out.write("						\r\n");
      out.write("						<div style=\"padding-top: 40px;\">\r\n");
      out.write("							<button type=\"button\" id=\"accident_al_sp\" class=\"btn btn-danger\" style=\"width: 48%; height: 50px;\">사고발생 공유</button>\r\n");
      out.write("							<button type=\"button\" id=\"accident_fin\" class=\"btn btn-success\" style=\"width: 48%; height: 50px; margin-left: 5px;\">사고수습 처리 완료</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div style=\"padding-top: 40px;\">\r\n");
      out.write("							<table style=\"width:100%\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width: 60%; padding-left: 50px;\">\r\n");
      out.write("										<img src=\"resources/images/sun.svg\">\r\n");
      out.write("									</td>\r\n");
      out.write("									<td style=\"width: 40%; font-size: 20px; padding-left: 10px;\">\r\n");
      out.write("										17℃ 남동<br>1.9 m/s\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"padding-top: 20px;padding-left: 20px;\">\r\n");
      out.write("							<table style=\"width:100%\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width: 20%;\">강수확률 :</td>\r\n");
      out.write("									<td style=\"width: 30%;\">10%</td>\r\n");
      out.write("									<td style=\"width: 20%;\">강수량 :</td>\r\n");
      out.write("									<td style=\"width: 30%;\">-</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width: 20%;\">최저/최고 : </td>\r\n");
      out.write("									<td style=\"width: 30%;\">11.2 / 21.3</td>\r\n");
      out.write("									<td style=\"width: 20%;\">습도 :</td>\r\n");
      out.write("									<td style=\"width: 30%;\">40.3%</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"padding-top: 20px;\">\r\n");
      out.write("							<table style=\"width:100%\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td rowspan=\"2\" style=\"width: 40%; padding-left: 20px;\">미세먼지 PM10 :</td>\r\n");
      out.write("									<td rowspan=\"2\" style=\"width: 20%; padding-left: 20px;\">\r\n");
      out.write("										<img src=\"resources/images/item01.png\" style=\"width: 20px;\">\r\n");
      out.write("									</td>\r\n");
      out.write("									<td style=\"width: 40%; padding-left: 10px;\">36(1H)\r\n");
      out.write("									</td>									\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td style=\"width: 40%; padding-left: 10px;\">89(24H)\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		</nav>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<button type=\"button\" class=\"hamburger is-open\" data-toggle=\"offcanvas\"></button>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	plusButton =document.querySelector(\".button2\");\r\n");
      out.write("	plusButton.addEventListener(\"click\", plusInput);\r\n");
      out.write("	minusButton =document.querySelector(\".button1\");\r\n");
      out.write("	minusButton.addEventListener(\"click\", minusInput);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/jsp/main/home3.jsp(15,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../include/css_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/jsp/main/home3.jsp(16,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../include/js_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
