/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-19 09:04:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TestGIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642397204384L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 request.setCharacterEncoding("utf-8"); 
      out.write('\n');
 response.setContentType("text/html;charset=UTF-8"); 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=10\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Web GIS 테스트 - 유해물질 재난안전</title>\n");
      out.write("\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- header -->\n");
      out.write("	<!--\n");
      out.write("	<nav class=\"navbar-static-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"navbar-header\">\n");
      out.write("				<a class=\"navbar-brand\" href=\"#\">유해물질 재난안전 정보 확인 서비스</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	-->\n");
      out.write("	<!-- contents -->\n");
      out.write("	<div id=\"page-content-wrapper\">\n");
      out.write("		<div id=\"alarm-dim-layer\" class=\"dim-layer\">\n");
      out.write("		    <div class=\"dimBg\"></div>\n");
      out.write("		    <div id=\"layer2\" class=\"pop-layer\">\n");
      out.write("		        <div class=\"pop-container\">\n");
      out.write("		            <div class=\"pop-conts\">\n");
      out.write("		                <p class=\"ctxt mb20\">유해물질 유출 대피 알림<br>염화티오닐(Thionyl chloride)</p>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		    </div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div id=\"msg-dim-layer\" class=\"dim-layer\">\n");
      out.write("		    <div class=\"dimBg\"></div>\n");
      out.write("		    <div id=\"layer2\" class=\"pop-layer\">\n");
      out.write("		    	<div class=\"closeX closeXp\">x</div>\n");
      out.write("		        <div class=\"pop-container\">\n");
      out.write("		            <div class=\"pop-conts\">\n");
      out.write("		                <p class=\"ctxt mb20\"></p>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		    </div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div id=\"map\">\n");
      out.write("			<canvas id=\"windyMap\" class=\"fill\"></canvas>\n");
      out.write("			\n");
      out.write("			<div id=\"pixel_box\">\n");
      out.write("				<div class=\"closeX\">x</div>\n");
      out.write("				<div id=\"overlay-ses\"></div>\n");
      out.write("			</div>\n");
      out.write("<!-- \n");
      out.write("			<div id=\"pixel_box1\">\n");
      out.write("				<div class=\"panel-heading\">\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">사고정보</h4>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses2\">\n");
      out.write("					<div class=\"category\">\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px;\">\n");
      out.write("							<div class=\"item-title fl w-30\"><h4>발생시각 : </h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\" id=\"currentTime\"><h4></h4></div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item cf\">\n");
      out.write("							<div class=\"item-title fl w-30\"><h4>사고진행 : </h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\" id=\"runningTime\"><h4></h4></div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item cf\" style=\"margin-bottom: 10px;\">\n");
      out.write("							<button id=\"res2accident\" type=\"button\" class=\"btn btn-danger\" style=\"width: 45%; height: 30px;\">대응요령</button>\n");
      out.write("							<button id=\"resSystem\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 30px; margin-left: 5px;margin-right:10px\">대응체계</button>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write(" -->\n");
      out.write(" <!--\n");
      out.write("			<div id=\"pixel_box4\">\n");
      out.write("				<div class=\"panel-heading\">\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">지도 on/off</h4>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses2\" style=\"padding-top: 5px;\">\n");
      out.write("					<div class=\"category\">\n");
      out.write("						<div class=\"item cf\" style=\"margin-bottom: 10px;\">\n");
      out.write("							<button id=\"map_onoff_spread\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 40px;\">확산 Map on</button>\n");
      out.write("							<button id=\"map_onoff_wind\" type=\"button\" class=\"btn btn-success\" style=\"width: 45%; height: 40px; margin-left: 5px;margin-right:10px\">바람 Map on</button>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write(" -->\n");
      out.write(" <!--	\n");
      out.write("			<div id=\"pixel_box2\">\n");
      out.write("				<div class=\"panel-heading\">\n");
      out.write("					<h4 style=\"font-size: 18px; margin-top: 5px\">대응상황</h4>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"overlay-ses2\" class=\"overlay-ses3\">\n");
      out.write("					<div class=\"category\">\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px; background-color: #d9534f\">\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>1단계</h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>화학사고 발생,<br>사고접수 및 전파</h4></div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>2단계</h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>위기대응반 가동</h4></div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>3단계</h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>화학사고 수습본부<br>설치 및 사고수습</h4></div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item cf\" style=\"text-align-last: center;\">\n");
      out.write("							<img src=\"resources/images/arrow_down.png\" style=\"padding: 10px 0px; width: 20%;\">\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div class=\"item cf\" style=\"background-color: #6d6767\">\n");
      out.write("							<div class=\"item-title fl w-30\" style=\"padding-left: 5px\"><h4>4단계</h4></div>\n");
      out.write("							<div class=\"item-number fl w-60\"><h4>사고지역 복구 및<br>사고 후 영향조사,<br>종료</h4></div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write(" -->\n");
      out.write("<!--				\n");
      out.write("			<div id=\"pixel_box3\">\n");
      out.write("				<div class=\"closeX\">x</div>\n");
      out.write("				<div id=\"overlay-ses2\" style=\"padding-left: 10px;\">\n");
      out.write("					<div class=\"category\">\n");
      out.write("						<div class=\"item cf\" style=\"margin-top: 10px;\">\n");
      out.write("							<img id=\"pixel_box3_img\" src=\"resources/images/res2accident.PNG\" style=\"width: 700px; padding-right: 10px; padding-bottom: 10px;\">\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("<!--	\n");
      out.write("	<div id=\"wrapper\" class=\"toggled\">\n");
      out.write("	\n");
      out.write("		<nav id=\"sidebar-wrapper\">\n");
      out.write("			<div class=\"accordion-group panel\">\n");
      out.write("				<div class=\"panel-heading\" data-parent=\"#sidebar-wrapper\" href=\"#collapse1\">\n");
      out.write("					<h4 class=\"panel-title\"><a href=\"#\">대피소 안내</a></h4>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"collapse1\" class=\"collapse in\">\n");
      out.write("					<div class=\"panel-body\">\n");
      out.write("						<div>\n");
      out.write("							<table>\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"padding: 0px 0px 5px 0px\">\n");
      out.write("										<img src=\"resources/images/current_location.png\" style=\"width: 30px; height: 30px;\"> 현 위치 :\n");
      out.write("									</td>\n");
      out.write("									<td style=\"padding: 0px 0px 5px 5px\">\n");
      out.write("										<span id=\"address\"></span>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("						<div style=\"width: 100%; border-bottom: 1px solid white;\"></div>\n");
      out.write("						<div style=\"padding-top: 5px\">\n");
      out.write("							<ul class=\"nav nav-pills mb-3\" id=\"pills-tab\" role=\"tablist\">\n");
      out.write("								<li class=\"nav-item\" style=\"width: 31%; text-align: center;\">\n");
      out.write("							    	<a class=\"nav-link active\" id=\"pills-all-tab\" data-toggle=\"pill\" href=\"#pills-all\" role=\"tab\" aria-controls=\"pills-all\" aria-selected=\"true\">전체</a>\n");
      out.write("								</li>\n");
      out.write("							  	<li class=\"nav-item\" style=\"width: 31%; text-align: center;\">\n");
      out.write("							    	<a class=\"nav-link\" id=\"pills-normal-tab\" data-toggle=\"pill\" href=\"#pills-normal\" role=\"tab\" aria-controls=\"pills-normal\" aria-selected=\"false\">안전지역</a>\n");
      out.write("							  	</li>\n");
      out.write("							  	<li class=\"nav-item\" style=\"width: 31%; text-align: center;\">\n");
      out.write("								    <a class=\"nav-link\" id=\"pills-rapid-tab\" data-toggle=\"pill\" href=\"#pills-rapid\" role=\"tab\" aria-controls=\"pills-rapid\" aria-selected=\"false\">긴급대피</a>\n");
      out.write("							  	</li>\n");
      out.write("							</ul>\n");
      out.write("							<div style=\"width: 100%; border-bottom: 1px solid white;\"></div>\n");
      out.write("							<div class=\"tab-content\" id=\"pills-tabContent\" style=\"height: 200px;\">\n");
      out.write("					  			<div class=\"tab-pane fade active\" id=\"pills-all\" role=\"tabpanel\" aria-labelledby=\"pills-all-tab\">\n");
      out.write("					  				<table id=\"pills-all-table\" style=\"width:100%\">\n");
      out.write("										<tbody>\n");
      out.write("										</tbody>\n");
      out.write("					  				</table>\n");
      out.write("					  			</div>\n");
      out.write("					  			<div class=\"tab-pane fade\" id=\"pills-normal\" role=\"tabpanel\" aria-labelledby=\"pills-normal-tab\">\n");
      out.write("					  				<table id=\"pills-normal-table\" style=\"width:100%\">\n");
      out.write("										<tbody>\n");
      out.write("										</tbody>\n");
      out.write("					  				</table>\n");
      out.write("					  			</div>\n");
      out.write("					  			<div class=\"tab-pane fade\" id=\"pills-rapid\" role=\"tabpanel\" aria-labelledby=\"pills-rapid-tab\">\n");
      out.write("					  				<table id=\"pills-rapid-table\" style=\"width:100%\">\n");
      out.write("										<tbody>\n");
      out.write("										</tbody>\n");
      out.write("					  				</table>\n");
      out.write("					  			</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"accordion-group panel\">\n");
      out.write("				<div class=\"panel-heading\" data-parent=\"#sidebar-wrapper\" href=\"#collapse2\">\n");
      out.write("					<h4 class=\"panel-title\"><a href=\"#\">사고 상세 정보</a></h4>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"collapse2\" class=\"collapse in\">\n");
      out.write("					<div class=\"panel-body\">\n");
      out.write("						<div>\n");
      out.write("							<table style=\"width:100%\">\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width:30%; padding-bottom:10px\">사고위치 :</td>\n");
      out.write("									<td id=\"accident\" style=\"width:70%; padding-bottom: 10px;\"></td>\n");
      out.write("								</tr>\n");
      out.write("								\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width:30%; padding-bottom:10px\">사고물질 :</td>\n");
      out.write("									<td id=\"accidentMatrial\" style=\"width:70%; padding-bottom: 10px;\"></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("								<tr style=\"border-bottom: 1px solid white;\"><td colspan=\"2\"></tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<td rowspan=\"3\" style=\"width:30%; padding-bottom:10px\">확산예상범위 :<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(위험도)</td>\n");
      out.write("									<td style=\"width:70%;\">\n");
      out.write("										<span id=\"accident_area1\" style=\"background-color: #d9534f;display: block; padding-left: 10px; line-height: 30px;\"></span>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width:70%;\">\n");
      out.write("										<span id=\"accident_area2\" style=\"background-color: #ded30a;display: block; padding-left: 10px; line-height: 30px;\"></span>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width:70%;\">\n");
      out.write("										<span id=\"accident_area3\" style=\"background-color: #5cb85c;display: block; padding-left: 10px; line-height: 30px;\"></span>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div style=\"width: 100%; border-bottom: 1px solid white; padding-top: 10px;\"></div>\n");
      out.write("						\n");
      out.write("						<div style=\"padding-top: 40px;\">\n");
      out.write("							<button type=\"button\" id=\"accident_al_sp\" class=\"btn btn-danger\" style=\"width: 48%; height: 50px;\">사고발생 공유</button>\n");
      out.write("							<button type=\"button\" id=\"accident_fin\" class=\"btn btn-success\" style=\"width: 48%; height: 50px; margin-left: 5px;\">사고수습 처리 완료</button>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div style=\"padding-top: 40px;\">\n");
      out.write("							<table style=\"width:100%\">\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width: 60%; padding-left: 50px;\">\n");
      out.write("										<img src=\"resources/images/sun.svg\">\n");
      out.write("									</td>\n");
      out.write("									<td style=\"width: 40%; font-size: 20px; padding-left: 10px;\">\n");
      out.write("										17℃ 남동<br>1.9 m/s\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div style=\"padding-top: 20px;padding-left: 20px;\">\n");
      out.write("							<table style=\"width:100%\">\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width: 20%;\">강수확률 :</td>\n");
      out.write("									<td style=\"width: 30%;\">10%</td>\n");
      out.write("									<td style=\"width: 20%;\">강수량 :</td>\n");
      out.write("									<td style=\"width: 30%;\">-</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width: 20%;\">최저/최고 : </td>\n");
      out.write("									<td style=\"width: 30%;\">11.2 / 21.3</td>\n");
      out.write("									<td style=\"width: 20%;\">습도 :</td>\n");
      out.write("									<td style=\"width: 30%;\">40.3%</td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div style=\"padding-top: 20px;\">\n");
      out.write("							<table style=\"width:100%\">\n");
      out.write("								<tr>\n");
      out.write("									<td rowspan=\"2\" style=\"width: 40%; padding-left: 20px;\">미세먼지 PM10 :</td>\n");
      out.write("									<td rowspan=\"2\" style=\"width: 20%; padding-left: 20px;\">\n");
      out.write("										<img src=\"resources/images/item01.png\" style=\"width: 20px;\">\n");
      out.write("									</td>\n");
      out.write("									<td style=\"width: 40%; padding-left: 10px;\">36(1H)\n");
      out.write("									</td>									\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td style=\"width: 40%; padding-left: 10px;\">89(24H)\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("	\n");
      out.write("		</nav>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<button type=\"button\" class=\"hamburger is-open\" data-toggle=\"offcanvas\"></button>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write(" -->\n");
      out.write("		\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/jsp/main/home3.jsp(15,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../include/css_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/jsp/main/home3.jsp(16,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../include/js_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
