/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-24 04:31:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Sample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TestGIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642397204384L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("// 주소 객체를 담을 배열\r\n");
      out.write("let address = [];\r\n");
      out.write("// address.length=0;    3  address[0]\r\n");
      out.write("\r\n");
      out.write("function goPopup(){\r\n");
      out.write("	// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("	// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(https://www.juso.go.kr/addrlink/addrCoordUrl.do)를 호출하게 됩니다.\r\n");
      out.write("	var pop = window.open('popup.do',\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,detBdNmList,bdNm,bdKdcd,siNm,sggNm,emdNm,liNm,rn,udrtYn,buldMnnm,buldSlno,mtYn,lnbrMnnm,lnbrSlno,emdNo,entX,entY){\r\n");
      out.write("		// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("		document.form.roadFullAddr.value = roadFullAddr;\r\n");
      out.write("		document.form.roadAddrPart1.value = roadAddrPart1;\r\n");
      out.write("		document.form.roadAddrPart2.value = roadAddrPart2;\r\n");
      out.write("		document.form.addrDetail.value = addrDetail;\r\n");
      out.write("		document.form.engAddr.value = engAddr;\r\n");
      out.write("		document.form.jibunAddr.value = jibunAddr;\r\n");
      out.write("		document.form.zipNo.value = zipNo;\r\n");
      out.write("		document.form.admCd.value = admCd;\r\n");
      out.write("		document.form.rnMgtSn.value = rnMgtSn;\r\n");
      out.write("		document.form.bdMgtSn.value = bdMgtSn;\r\n");
      out.write("		document.form.detBdNmList.value = detBdNmList;\r\n");
      out.write("		document.form.bdNm.value = bdNm;\r\n");
      out.write("		document.form.bdKdcd.value = bdKdcd;\r\n");
      out.write("		document.form.siNm.value = siNm;\r\n");
      out.write("		document.form.sggNm.value = sggNm;\r\n");
      out.write("		document.form.emdNm.value = emdNm;\r\n");
      out.write("		document.form.liNm.value = liNm;\r\n");
      out.write("		document.form.rn.value = rn;\r\n");
      out.write("		document.form.udrtYn.value = udrtYn;\r\n");
      out.write("		document.form.buldMnnm.value = buldMnnm;\r\n");
      out.write("		document.form.buldSlno.value = buldSlno;\r\n");
      out.write("		document.form.mtYn.value = mtYn;\r\n");
      out.write("		document.form.lnbrMnnm.value = lnbrMnnm;\r\n");
      out.write("		document.form.lnbrSlno.value = lnbrSlno;\r\n");
      out.write("		document.form.emdNo.value = emdNo;\r\n");
      out.write("		document.form.entX.value = entX;\r\n");
      out.write("		document.form.entY.value = entY;\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		let local = {\r\n");
      out.write("		 addr : roadFullAddr,\r\n");
      out.write("		 X : entX,\r\n");
      out.write("		 Y : entY,\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		address.push(local);\r\n");
      out.write("		console.log(address);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<title>주소 검색</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"form\" id=\"form\" method=\"post\">\r\n");
      out.write("	<input type=\"button\" onClick=\"goPopup();\" value=\"검색검색\"/>\r\n");
      out.write("	<div id=\"list\"></div>\r\n");
      out.write("	<div id=\"callBackDiv\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr><td>도로명주소 전체(포멧)</td><td><input type=\"text\"  style=\"width:500px;\" id=\"roadFullAddr\"  name=\"roadFullAddr\" /></td></tr>\r\n");
      out.write("			<tr><td>도로명주소           </td><td><input type=\"text\"  style=\"width:500px;\" id=\"roadAddrPart1\"  name=\"roadAddrPart1\" /></td></tr>\r\n");
      out.write("			<tr><td>고객입력 상세주소    </td><td><input type=\"text\"  style=\"width:500px;\" id=\"addrDetail\"  name=\"addrDetail\" /></td></tr>\r\n");
      out.write("			<tr><td>참고주소             </td><td><input type=\"text\"  style=\"width:500px;\" id=\"roadAddrPart2\"  name=\"roadAddrPart2\" /></td></tr>\r\n");
      out.write("			<tr><td>영문 도로명주소      </td><td><input type=\"text\"  style=\"width:500px;\" id=\"engAddr\"  name=\"engAddr\" /></td></tr>\r\n");
      out.write("			<tr><td>지번                 </td><td><input type=\"text\"  style=\"width:500px;\" id=\"jibunAddr\"  name=\"jibunAddr\" /></td></tr>\r\n");
      out.write("			<tr><td>우편번호             </td><td><input type=\"text\"  style=\"width:500px;\" id=\"zipNo\"  name=\"zipNo\" /></td></tr>\r\n");
      out.write("			<tr><td>행정구역코드        </td><td><input type=\"text\"  style=\"width:500px;\" id=\"admCd\"  name=\"admCd\" /></td></tr>\r\n");
      out.write("			<tr><td>도로명코드          </td><td><input type=\"text\"  style=\"width:500px;\" id=\"rnMgtSn\"  name=\"rnMgtSn\" /></td></tr>\r\n");
      out.write("			<tr><td>건물관리번호        </td><td><input type=\"text\"  style=\"width:500px;\" id=\"bdMgtSn\"  name=\"bdMgtSn\" /></td></tr>\r\n");
      out.write("			<tr><td>상세번물명        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"detBdNmList\"  name=\"detBdNmList\" /></td></tr>\r\n");
      out.write("			<tr><td>건물명        		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"bdNm\"  name=\"bdNm\" /></td></tr>\r\n");
      out.write("			<tr><td>공동주택여부       </td><td><input type=\"text\"  style=\"width:500px;\" id=\"bdKdcd\"  name=\"bdKdcd\" /></td></tr>\r\n");
      out.write("			<tr><td>시도명        		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"siNm\"  name=\"siNm\" /></td></tr>\r\n");
      out.write("			<tr><td>시군구명        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"sggNm\"  name=\"sggNm\" /></td></tr>\r\n");
      out.write("			<tr><td>읍면동명        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"emdNm\"  name=\"emdNm\" /></td></tr>\r\n");
      out.write("			<tr><td>법정리명        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"liNm\"  name=\"liNm\" /></td></tr>\r\n");
      out.write("			<tr><td>도로명        		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"rn\"  name=\"rn\" /></td></tr>\r\n");
      out.write("			<tr><td>지하여부        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"udrtYn\"  name=\"udrtYn\" /></td></tr>\r\n");
      out.write("			<tr><td>건물본번        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"buldMnnm\"  name=\"buldMnnm\" /></td></tr>\r\n");
      out.write("			<tr><td>건물부번        	</td><td><input type=\"text\"  style=\"width:500px;\" id=\"buldSlno\"  name=\"buldSlno\" /></td></tr>\r\n");
      out.write("			<tr><td>산여부        		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"mtYn\"  name=\"mtYn\" /></td></tr>\r\n");
      out.write("			<tr><td>지번본번(번지)     </td><td><input type=\"text\"  style=\"width:500px;\" id=\"lnbrMnnm\"  name=\"lnbrMnnm\" /></td></tr>\r\n");
      out.write("			<tr><td>지번부번(호)       </td><td><input type=\"text\"  style=\"width:500px;\" id=\"lnbrSlno\"  name=\"lnbrSlno\" /></td></tr>\r\n");
      out.write("			<tr><td>읍면동일련번호		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"emdNo\"  name=\"emdNo\" /></td></tr>\r\n");
      out.write("			<tr><td>X 좌표       		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"entX\"  name=\"entX\" /></td></tr>\r\n");
      out.write("			<tr><td>Y 좌표       		</td><td><input type=\"text\"  style=\"width:500px;\" id=\"entY\"  name=\"entY\" /></td></tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 	map.getView().setCenter(center); -->\r\n");
      out.write("	\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var firstProjection = \"+proj=tmerc +lat_0=38 +lon_0=127.5 +k=0.9996 +x_0=1000000 +y_0=2000000 +ellps=GRS80 +units=m +no_defs\"; //from\r\n");
      out.write("var secondProjection = \"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs\"; //to\r\n");
      out.write("//I'm not going to redefine those two in latter examples.\r\n");
      out.write("console.log(proj4(firstProjection, secondProjection, [document.getElementById(\"entX\").value,document.getElementById(\"entY\").value])); // Convert 하려는 좌표\r\n");
      out.write("ol.proj.transform([127.0000, 37.5317], 'EPSG:4326', 'EPSG:3857');\r\n");
      out.write("pan(,)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/jsp/main/Sample.jsp(10,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../include/css_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/jsp/main/Sample.jsp(11,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../include/js_define.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
